#!/bin/sh
# git config core.hooksPath hooks
echo '[git hook] executing maven spotless:write before commit'

# stash any unstaged changes
# git stash -q --keep-index

mvn -f "./pom.xml" com.hubspot.maven.plugins:prettier-maven-plugin:write

# unstash the unstashed changes
# git stash pop -q

changed_java_files=$(git diff --cached --name-only --diff-filter=ACMR | grep ".*java$" )

if [ -n "$changed_java_files" ]; then
    git add $changed_java_files
fi

# store the last exit code in a variable
RESULT=$?

# return the './gradlew spotlessCheck' exit code
exit $RESULT