#!/bin/sh
# git config core.hooksPath hooks
echo '[git hook] executing maven spotless:check before commit'

# stash any unstaged changes
git stash -q --keep-index

mvn -f "./pom.xml" com.diffplug.spotless:spotless-maven-plugin:check

# store the last exit code in a variable
RESULT=$?

# unstash the unstashed changes
git stash pop -q

# return the './gradlew spotlessCheck' exit code
exit $RESULT